### ISSUE TITLE
latent=None，结果崩了

### ISSUE THREAD

**Issue by Monalissaa** [zituitui/BELM#3]
再次感谢您的优秀工作。
我尝试了将latent设置为None进行BELM的latent to intermediate和intermediate to latent，但是重构出来的图崩了，如下，请问这种情况是正常的嘛？如果不正常，应该怎么改呀？
![image](https://github.com/user-attachments/assets/f6c304bc-682b-4a76-a31d-577b55974fd7)

**Comment by zituitui** [comment]
将latent设置为None的话，会random一个latent，这样的latent就算exact inversion来回之后也应该得不到有意义的图像。

**Comment by Monalissaa** [comment]
可以用BELM采样来得到一个由random latent生成的正常图像嘛？

**Comment by zituitui** [comment]
可以的，直接调用intermediate_to_latent并设置latent=None就行了。这时候会随机一个x_T，然后走完采样链路，得到一个x_0图像

**Comment by Monalissaa** [comment]
解决了，感谢🙏
