### ISSUE TITLE
如何使用BELM scheduler正常生成一张图片

### ISSUE THREAD

**Issue by yypyyds** [zituitui/BELM#5]
我初始化了一个高斯噪声$z_T$，然后使用这个高斯噪声，调用`BELM.rev_forward`生成图片，但是我生成的图片是这样的
![image](https://github.com/user-attachments/assets/846ac737-ff6b-49f5-8d6a-180b56421ec4)

是哪里设置出错了吗，我的代码如下：
```Python
import torch
from diffusers import StableDiffusionPipeline, DDIMScheduler
from samplers.utils import PipelineLike
from samplers import BELM
model_id = "stabilityai/stable-diffusion-2-1"
guidance_scale = 2.0
num_inference_steps = 50
device="cuda"

sche = DDIMScheduler(beta_end=0.012, beta_start=0.00085, beta_schedule='scaled_linear', clip_sample=False,
                         timestep_spacing='linspace', set_alpha_to_one=False)
sd = StableDiffusionPipeline.from_pretrained(model_id, local_files_only=True, scheduler=sche)

sd_pipe = PipelineLike(device=device, vae=sd.vae, text_encoder=sd.text_encoder, tokenizer=sd.tokenizer,
                     unet=sd.unet, scheduler=sche)
sd_pipe.vae.to(device)
sd_pipe.text_encoder.to(device)
sd_pipe.unet.to(device)
ori_latent = torch.randn((1,4,64,64), device="cuda")
sd_params = {'prompt': 'castle by the river', 'negative_prompt': '', 'seed': 1, 'guidance_scale': guidance_scale,
            'num_inference_steps': 50, 'width': 512, 'height': 512}
image = BELM.rev_forward(sd_pipe, sd_params, ori_latent)
image.save("belm.jpg")
```

**Comment by yypyyds** [comment]
在其他Issue里看到用`BELM.intermediate_to_latent`生成，试过了也不行

**Comment by zituitui** [comment]
您好
我新加了使用BELM以及其他采样器的正常采样script：
https://github.com/zituitui/BELM/blob/main/scripts/sd_sampling.py
这是我在prompt = 'A dog', negative_prompt='',--num_inference_steps 100 --guidance 5.0之下的采样结果：
![belm_infer100_g5 0](https://github.com/user-attachments/assets/6defc1b1-8747-47a1-9487-6f38e961e255)


关于您的问题，可以试试datatype改为fp32，或者sd版本使用2-base

**Comment by yypyyds** [comment]
> 您好 我新加了使用BELM以及其他采样器的直接采样script： https://github.com/zituitui/BELM/blob/main/scripts/sd_sampling.py 这是我在prompt = 'A dog', negative_prompt='',num_inference_steps =100, guidance=5.0,sd-v15之下使用BELM的采样结果： ![belm_infer100_g5 0](https://private-user-images.githubusercontent.com/65052672/384233182-6defc1b1-8747-47a1-9487-6f38e961e255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTEzNjcsIm5iZiI6MTczMTA1MTA2NywicGF0aCI6Ii82NTA1MjY3Mi8zODQyMzMxODItNmRlZmMxYjEtODc0Ny00N2ExLTk0ODctNmYzOGU5NjFlMjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA3MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZjhmMWY3ZmFkZGE2OTgyOGQyYTdhZmQwZmZjZmM5YWUyZDNlMGUzOWQ0OTIwYjI0ZjM2NDg3ODA1OGEzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tXrOhdrLQ3yiqy7BtrtHoTabkRLOmAD5eR8ARZCcxPE)
> 
> 关于您的问题，可以试试datatype改为fp32，或者sd版本使用2-base

感谢您的回复！我换成2-base之后问题解决了
但是我在重建过程中遇到了一个新的问题，想请教一下
我使用一个携带信息的初始噪声Z_T作为`BELM.intermediate_to_latent`的参数`intermediate`，生成了`result_latent`
然后我调用`BELM.latent_to_intermediate`，将`result_latent`作为Z_0获得初始噪声
然后计算两个Z_T的mse，得到的值很大
以下是我这部分的代码
```python
sd_params = {'prompt': prompt, 'negative_prompt': negative_prompt, 'seed': 38018716,
                'guidance_scale': guidance_scale,
                'num_inference_steps': num_inference_steps, 'width': 512, 'height': 512}

# ori_latent为服从高斯分布的携带信息的latent
result_latent = BELM.intermediate_to_latent(
    sd_pipe=sd_pipe, sd_params=sd_params,
    intermediate=ori_latent,
    intermediate_second=None,freeze_step=0,
    device=device
    )
intermediate, second_intermediate = BELM.latent_to_intermediate(sd_pipe=sd_pipe, sd_params=sd_params, latent=result_latent, device=device)
latent1 = intermediate.detach().cpu().numpy()
latent2 = ori_latent.detach().cpu().numpy()
mse = np.mean((latent1-latent2)**2)
print(mse)
```
mse的值为
```bash
0.589747
```
这和从图片开始重建的结果相差很大，我要如何才能得到这个初始噪声呢？

**Comment by yinchunji** [comment]
> > 您好 我新加了使用BELM以及其他采样器的直接采样script： https://github.com/zituitui/BELM/blob/main/scripts/sd_sampling.py 这是我在prompt = 'A dog', negative_prompt='',num_inference_steps =100, guidance=5.0,sd-v15之下使用BELM的采样结果： ![belm_infer100_g5 0](https://private-user-images.githubusercontent.com/65052672/384233182-6defc1b1-8747-47a1-9487-6f38e961e255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNTEzNjcsIm5iZiI6MTczMTA1MTA2NywicGF0aCI6Ii82NTA1MjY3Mi8zODQyMzMxODItNmRlZmMxYjEtODc0Ny00N2ExLTk0ODctNmYzOGU5NjFlMjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA3MzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZjhmMWY3ZmFkZGE2OTgyOGQyYTdhZmQwZmZjZmM5YWUyZDNlMGUzOWQ0OTIwYjI0ZjM2NDg3ODA1OGEzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tXrOhdrLQ3yiqy7BtrtHoTabkRLOmAD5eR8ARZCcxPE)
> > 关于您的问题，可以试试datatype改为fp32，或者sd版本使用2-base
> 
> 感谢您的回复！我换成2-base之后问题解决了 但是我在重建过程中遇到了一个新的问题，想请教一下 我使用一个携带信息的初始噪声Z_T作为`BELM.intermediate_to_latent`的参数`intermediate`，生成了`result_latent` 然后我调用`BELM.latent_to_intermediate`，将`result_latent`作为Z_0获得初始噪声 然后计算两个Z_T的mse，得到的值很大 以下是我这部分的代码
> 
> ```python
> sd_params = {'prompt': prompt, 'negative_prompt': negative_prompt, 'seed': 38018716,
>                 'guidance_scale': guidance_scale,
>                 'num_inference_steps': num_inference_steps, 'width': 512, 'height': 512}
> 
> # ori_latent为服从高斯分布的携带信息的latent
> result_latent = BELM.intermediate_to_latent(
>     sd_pipe=sd_pipe, sd_params=sd_params,
>     intermediate=ori_latent,
>     intermediate_second=None,freeze_step=0,
>     device=device
>     )
> intermediate, second_intermediate = BELM.latent_to_intermediate(sd_pipe=sd_pipe, sd_params=sd_params, latent=result_latent, device=device)
> latent1 = intermediate.detach().cpu().numpy()
> latent2 = ori_latent.detach().cpu().numpy()
> mse = np.mean((latent1-latent2)**2)
> print(mse)
> ```
> 
> mse的值为
> 
> ```shell
> 0.589747
> ```
> 
> 这和从图片开始重建的结果相差很大，我要如何才能得到这个初始噪声呢？

如果要完全重建intermediate，需要latent_to_intermediate中也输入类似intermediate_second的latent_second。我们会尽快更新latent_to_intermediate函数以支持intermediate的精确重建。

**Comment by yypyyds** [comment]
发现问题是用的旧版本的代码，latent_to_intermediate中少了epsilon
