### ISSUE TITLE
图像编辑的效果与论文原结果相差甚远

### ISSUE THREAD

**Issue by xugao97** [zituitui/BELM#6]
我将仓库中的图像编辑命令应用到论文中的“A woman” to "an angry woman"，得到的结果与论文相差甚远，需要什么别的设置吗？

**Comment by zituitui** [comment]
您好 
以我的经验，以下几个操作对图像编辑效果很重要：
1. 更多的步数
2. 小的cfg guidance
3. 灵活的freeze_step

**Comment by xugao97** [comment]
> 您好 以我的经验，以下几个操作对图像编辑效果很重要：
> 
> 1. 更多的步数
> 2. 小的cfg guidance
> 3. 灵活的freeze_step

感谢回复
